---
title: OLPC San Francisco | one laptop per child san francisco volunteer community
description: >-
  One Laptop Per Child San Franciso is a volunteer community.

url: "https://olpcsf.github.io"
baseurl: "/www.olpcsf.org"

permalink: pretty
exclude:
  - bin
  - env.sample
  - Gemfile
  - Gemfile.lock
  - README.md
