---
title: OLPC San Francisco | one laptop per child san francisco volunteer community
description: >-
  One Laptop Per Child San Franciso is a volunteer community.

baseurl: "/www.olpcsf.org"

source: src
